server:
  port: 9000
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lms?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding-utf8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123
mybatis:
  #  全局配置文件
  #  config-location: classpath:mybatis/mybatis-config.xml
  #  sql映射文件
  mapper-locations: classpath:/mapper/**/*.xml
  #  写了这个配置就不用写全局配置文件了
  configuration:
    map-underscore-to-camel-case: true